# Generated by Django 4.1.3 on 2023-05-04 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricChangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value_before', models.FloatField(blank=True, null=True, verbose_name='Значение до изменения')),
                ('value_after', models.FloatField(verbose_name='Значение после изменения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Изменение метрики',
                'verbose_name_plural': 'Изменения метрик',
                'ordering': ['-created'],
            },
        ),
    ]
