# Generated by Django 4.1.3 on 2023-05-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_changes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricchangemodel',
            name='value_before',
        ),
        migrations.AddField(
            model_name='metricchangemodel',
            name='station_id',
            field=models.CharField(default=0, max_length=20, verbose_name='Станция'),
            preserve_default=False,
        ),
    ]
