# Generated by Django 4.1.3 on 2023-05-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_changes', '0002_remove_metricchangemodel_value_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricchangemodel',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
