# Generated by Django 4.1.3 on 2022-12-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionNormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(choices=[('Max Temperature', 'Максимальная температура'), ('Min Temperature', 'Минимальная температура'), ('Precipitation Sum', 'Сумма осадков'), ('Max Wind Speed', 'Максимальная скорость ветра'), ('Dominant Wind Direction', 'Господствующее направление ветра')], max_length=25, verbose_name='Название метрики')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Норма для региона',
                'verbose_name_plural': 'Нормы для региона',
                'ordering': ['-date'],
            },
        ),
    ]
