# Generated by Django 4.1.3 on 2022-12-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_regionnormmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoistureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(choices=[('10 cm', '10 сантиметров'), ('20 cm', '20 сантиметров'), ('100 cm', '100 сантиметров')], max_length=25, verbose_name='Глубина почвы')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('date_and_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Метрика влажности почвы',
                'verbose_name_plural': 'Метрики влажности почвы',
                'ordering': ['-date_and_time'],
            },
        ),
    ]
