# Generated by Django 4.1.3 on 2023-02-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название культуры')),
                ('label', models.CharField(max_length=255, verbose_name='Описание')),
                ('max_permissible_precipitation_level', models.PositiveSmallIntegerField(verbose_name='Максимально допустимый уровень осадков (мм)')),
                ('min_permissible_precipitation_level', models.PositiveSmallIntegerField(verbose_name='Минимально допустимый уровень осадков (мм)')),
                ('vegetation_season_start', models.DateField(verbose_name='Начало вегетационного периода')),
                ('vegetation_season_end', models.DateField(verbose_name='Конец вегетационного периода')),
            ],
            options={
                'verbose_name': 'Агрокультура',
                'verbose_name_plural': 'Агрокультуры',
                'ordering': ['created'],
            },
        ),
        migrations.AddConstraint(
            model_name='agriculturemodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_agriculture_name'),
        ),
    ]
