# Generated by Django 4.1.3 on 2023-05-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturemodel',
            name='max_active_temperature_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Максимальный уровень суммы активных температур (С)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agriculturemodel',
            name='min_active_temperature_level',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Минимальный уровень суммы активных температур (С)'),
            preserve_default=False,
        ),
    ]
