# Generated by Django 4.1.3 on 2023-02-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_usernotificationsmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotificationsmodel',
            options={'ordering': ['created'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='usernotificationsmodel',
            name='notification_type',
            field=models.CharField(choices=[('COMMENT_CREATED', 'Комментарий создан')], max_length=128, null=True, verbose_name='Тип уведомления'),
        ),
    ]
