# Generated by Django 4.1.3 on 2023-05-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_changes', '0003_alter_metricchangemodel_date'),
        ('comments', '0002_alter_usercommentsmodel_options'),
        ('notifications', '0003_alter_usernotificationsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsmodel',
            name='metric_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics_changes.metricchangemodel', verbose_name='Изменение метрки'),
        ),
        migrations.AlterField(
            model_name='usernotificationsmodel',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.usercommentsmodel', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='usernotificationsmodel',
            name='notification_type',
            field=models.CharField(choices=[('COMMENT_CREATED', 'Комментарий создан'), ('METRICS_UPDATED', 'Метрика обновлена')], max_length=128, null=True, verbose_name='Тип уведомления'),
        ),
    ]
