# Generated by Django 4.1.3 on 2023-05-22 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('param_type', models.CharField(choices=[('temperature', 'температура'), ('wind', 'ветер'), ('humidity', 'влажность воздуха'), ('charge', 'заряд АКБ'), ('solar radiation', 'солнечная радиация'), ('precipitation', 'осадки')], max_length=128, verbose_name='Тип параметра')),
                ('min', models.FloatField(blank=True, null=True, verbose_name='Минимум')),
                ('max', models.FloatField(blank=True, null=True, verbose_name='Максимум')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка сообщений об отклонении параметра',
                'verbose_name_plural': 'Настройки сообщений об отклонении параметра',
                'abstract': False,
            },
        ),
    ]
